function drawFixation(cfg)
    % Draw gap around fixation
    Screen('FillOval', cfg.screen.win, cfg.color.background, ...
        CenterRect( ...
        [0 0 ...
        cfg.fixation.sizePix + 10 ...
        cfg.fixation.sizePix + 10], cfg.screen.winRect));

    % Draw fixation
    Screen('FillOval', cfg.screen.win, cfg.color.foreground, ...
        CenterRect( ...
        [0 0 cfg.fixation.sizePix cfg.fixation.sizePix], ...
        cfg.screen.winRect));
end
