function drawFixation(cfg, expParameters)
    % Draw gap around fixation
    Screen('FillOval', cfg.win, cfg.backgroundColor, ...
        CenterRect( ...
        [0 0 ...
        expParameters.fixationSizePix + 10 ...
        expParameters.fixationSizePix + 10], cfg.winRect));
    
    % Draw fixation
    Screen('FillOval', cfg.win, cfg.foregroundColor, ...
        CenterRect( ...
        [0 0 expParameters.fixationSizePix expParameters.fixationSizePix], ...
        cfg.winRect));
end